# Generated by Django 2.2.2 on 2019-07-26 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogerprofile', '0002_auto_20190726_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramImags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_url', models.CharField(max_length=1000)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogerprofile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='YTUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_urls', models.CharField(max_length=1000)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogerprofile.Profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Inlines',
        ),
    ]
