# Generated by Django 2.2.2 on 2019-07-26 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogerprofile', '0003_auto_20190726_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bloger',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='blogerprofile.Profile', verbose_name='Блогер:'),
            preserve_default=False,
        ),
    ]
