# Generated by Django 2.2.2 on 2019-07-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogerprofile', '0004_product_bloger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bloger',
        ),
    ]
