# Generated by Django 2.2.2 on 2019-07-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogerprofile', '0006_product_bloger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='BlogerCategory',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='BlogerProduct',
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='BlogerProfile',
        ),
    ]
