# Generated by Django 2.2.2 on 2019-07-26 16:12

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Особенные продукты:'),
        ),
        migrations.CreateModel(
            name='ShirtSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название:')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение товара:')),
                ('description', models.TextField(blank=True, verbose_name='Описание:')),
                ('size_s', models.BooleanField(default=True, verbose_name='S:')),
                ('size_m', models.BooleanField(default=True, verbose_name='M:')),
                ('size_l', models.BooleanField(default=True, verbose_name='L:')),
                ('size_xl', models.BooleanField(default=True, verbose_name='XL:')),
                ('size_2xl', models.BooleanField(default=True, verbose_name='2XL:')),
                ('size_3xl', models.BooleanField(default=True, verbose_name='3XL:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена:')),
                ('sale_on', models.BooleanField(blank=True, default=False, verbose_name='Роспродажа:')),
                ('sale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена на скидке:')),
                ('available', models.BooleanField(blank=True, default=True, verbose_name='Доступен:')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bloger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Blogers', verbose_name='Блогер:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='Категория:')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
