# Generated by Django 2.2.2 on 2019-07-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190726_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shirtsubscription',
            options={'ordering': ('price',), 'verbose_name': 'Прадукти'},
        ),
        migrations.AlterIndexTogether(
            name='shirtsubscription',
            index_together={('id', 'slug')},
        ),
    ]
