# Generated by Django 2.2.2 on 2019-07-26 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190726_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_urls', models.CharField(max_length=1000)),
                ('insta_url', models.CharField(max_length=1000)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Blogers')),
            ],
        ),
        migrations.DeleteModel(
            name='YTUrls',
        ),
    ]
