# Generated by Django 2.2.2 on 2019-07-30 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190726_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=15, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=15, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?7?\\d{9,15}$')], verbose_name='Телефон')),
                ('company', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Компания')),
                ('address1', models.CharField(db_index=True, max_length=40, verbose_name='Адрес 1')),
                ('address2', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Адрес 2')),
                ('city', models.CharField(db_index=True, max_length=15, verbose_name='Город')),
                ('country', models.CharField(db_index=True, max_length=15, verbose_name='Страна')),
                ('zip_code', models.IntegerField(db_index=True, max_length=6, verbose_name='ZIP')),
            ],
        ),
    ]
