# Generated by Django 2.2.2 on 2019-07-30 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.IntegerField(db_index=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{0,10}$')], verbose_name='ZIP'),
        ),
    ]
