# Generated by Django 2.2.2 on 2019-07-30 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190730_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(999999)], verbose_name='ZIP'),
        ),
    ]
