# Generated by Django 2.2.2 on 2019-07-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190730_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.IntegerField(db_index=True, max_length=6, verbose_name='ZIP'),
        ),
    ]
