# Generated by Django 2.2.2 on 2019-07-30 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20190730_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(3)], verbose_name='ZIP'),
        ),
    ]
