# Generated by Django 2.2.2 on 2019-07-30 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20190730_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(3)], verbose_name='ZIP'),
        ),
    ]
