# Generated by Django 2.2.2 on 2019-07-30 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20190730_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.RegexValidator('^\\d{3,6}$')], verbose_name='ZIP'),
        ),
    ]
